### ISSUE TITLE
Flaky test: test_import_code_in_notebooks

### ISSUE THREAD

**Issue by artemlops** [neuro-inc/cookiecutter-neuro-project#190]
see failed builds 
https://circleci.com/gh/neuromation/cookiecutter-neuro-project/841
https://circleci.com/gh/neuromation/cookiecutter-neuro-project/842
https://circleci.com/gh/neuromation/cookiecutter-neuro-project/843

after that, green build (the only change applied was not connected to the test: https://github.com/neuromation/cookiecutter-neuro-project/pull/189):
https://circleci.com/workflow-run/f8c53844-641d-4f8a-a73a-9d3b0f7f6e28

**Comment by ayushkovskiy** [comment]
Another, different failure:
https://circleci.com/gh/neuromation/cookiecutter-neuro-project/848

this time, the `ipynb` file was found, but somehow `modules/` was not found.
```
[NbConvertApp] Converting notebook /test-project-ac42f3ca/notebooks/Untitled.ipynb to asciidoc
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting '/test-project-ac42f3ca/notebooks/Untitled.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
```

**Comment by ayushkovskiy** [comment]
[problem 1](https://842-204585942-gh.circle-artifacts.com/0/ouptut/output_test-project-a03dde47.log): 
```
[NbConvertApp] WARNING | pattern '/test-project-a03dde47/notebooks/Untitled.ipynb' matched no files
...
command terminated with exit code 255
```

[problem 2](https://841-204585942-gh.circle-artifacts.com/0/ouptut/output_test-project-28b51966.log)
```
[NbConvertApp] Converting notebook /test-project-28b51966/notebooks/Untitled.ipynb to asciidoc
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Error while converting '/test-project-28b51966/notebooks/Untitled.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.6/dist-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
from modules import hello_world
hello_world()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-2-1aeadae4d2ec>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mmodules[0m [0;32mimport[0m [0mhello_world[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mhello_world[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'modules'
ModuleNotFoundError: No module named 'modules'
```

**Comment by ayushkovskiy** [comment]
not urgent for `Jan2020` iteration: I have not seen this problem for long time

**Comment by YevheniiSemendiak** [comment]
outdated
